// File Generated by Codable tool
import Foundation
struct CarbonEightHourMax : Codable {
	let west : Double?
	let national : Double?
	let east : Double?
	let central : Double?
	let south : Double?
	let north : Double?

	enum CodingKeys: String, CodingKey {

		case west = "west"
		case national = "national"
		case east = "east"
		case central = "central"
		case south = "south"
		case north = "north"
	}

	init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: CodingKeys.self)
		west = try values.decodeIfPresent(Double.self, forKey: .west)
		national = try values.decodeIfPresent(Double.self, forKey: .national)
		east = try values.decodeIfPresent(Double.self, forKey: .east)
		central = try values.decodeIfPresent(Double.self, forKey: .central)
		south = try values.decodeIfPresent(Double.self, forKey: .south)
		north = try values.decodeIfPresent(Double.self, forKey: .north)
	}

}
