// File Generated by Codable tool
import Foundation
struct Items : Codable {
	let timestamp : String?
	let update_timestamp : String?
	let readings : Readings?

	enum CodingKeys: String, CodingKey {

		case timestamp = "timestamp"
		case update_timestamp = "update_timestamp"
		case readings = "readings"
	}

	init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: CodingKeys.self)
		timestamp = try values.decodeIfPresent(String.self, forKey: .timestamp)
		update_timestamp = try values.decodeIfPresent(String.self, forKey: .update_timestamp)
		readings = try values.decodeIfPresent(Readings.self, forKey: .readings)
	}

}
