// File Generated by Codable tool
import Foundation
struct RegionMetaData : Codable {
	let name : String?
	let label_location : LabelLocation?

	enum CodingKeys: String, CodingKey {

		case name = "name"
		case label_location = "label_location"
	}

	init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: CodingKeys.self)
		name = try values.decodeIfPresent(String.self, forKey: .name)
		label_location = try values.decodeIfPresent(LabelLocation.self, forKey: .label_location)
	}

}
